version: '3.8'

services:
  migrations:
    image: ${CI_REGISTRY_IMAGE}/api:${CI_COMMIT_SHORT_SHA}
    command: sh -c "yarn install --production=false && yarn migrate:run -d ./datasource.ts"
    environment:
      - NODE_CONFIG_ENV
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB= #database_name
      - POSTGRES_PASSWORD
      - ADMIN_PASSWORD
    networks:
      # поменять на сеть на такую, как используется в docker-compose.yml (PROJECT_NAME_backend:)

networks:
  # поменять на сеть на такую, как используется в docker-compose.yml (PROJECT_NAME_backend:)
    external: true
