export enum ERROR_TYPE {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  ENTITY_NOT_FOUND_ERROR = 'ENTITY_NOT_FOUND_ERROR',
  SERVICE_ERROR = 'SERVICE_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
  FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
  ENTITY_CONFLICT_ERROR = 'ENTITY_CONFLICT_ERROR',
}

export enum VALIDATION_ERROR {
  MISSING_FIELD = 'MISSING_FIELD',
  INVALID_URL = 'INVALID_URL',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_ENUM_VALUE = 'INVALID_ENUM_VALUE',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_STRING_LENGTH = 'INVALID_STRING_LENGTH',
  INVALID_STATUS = 'INVALID_STATUS',
  NOT_MATCHES_PATTERN = 'NOT_MATCHES_PATTERN',
  ARRAY_VALUES_MUST_BE_UNIQUE = 'ARRAY_VALUES_MUST_BE_UNIQUE',
}
