export enum AUTH_ERROR {
  EMAIL_IS_ALREADY_USED = 'EMAIL_IS_ALREADY_USED',
  EMAIL_IS_NOT_CONFIRMED = 'EMAIL_IS_NOT_CONFIRMED',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  EMAIL_IS_ALREADY_CONFIRMED = 'EMAIL_IS_ALREADY_CONFIRMED',
  TOO_MANY_EMAIL_CONFIRMATION_REQUESTS = 'TOO_MANY_EMAIL_CONFIRMATION_REQUESTS',
  EMAIL_CONFIRMATION_TOKEN_NOT_FOUND = 'EMAIL_CONFIRMATION_TOKEN_NOT_FOUND',
  EMAIL_CONFIRMATION_TOKEN_EXPIRED = 'EMAIL_CONFIRMATION_TOKEN_EXPIRED',
}
