export enum TFA_ERROR {
  TFA_SECRET_ALREADY_EXISTS = 'TFA_SECRET_ALREADY_EXISTS',
  INCORRECT_TFA_CODE = 'INCORRECT_TFA_CODE',
  TFA_INVALID_STATUS = 'TFA_INVALID_STATUS',
  TFA_STEP_REQUIRED = 'TFA_STEP_REQUIRED',
}
